version: 2

sources:
  - name: staging
    database: "{{ env_var('DBT_BIGQUERY_PROJECT', 'kestra-sandbox-449620') }}"
    schema: "{{ env_var('DBT_BIGQUERY_SOURCE_DATASET', 'zoomcamp_week4_hw') }}"
    tables:
      - name: green_tripdata_ext
      - name: yellow_tripdata_ext
      - name: fhv_tripdata_ext

models:
  - name: stg_green_tripdata
    description: "Staging table for Green Taxi trip data"
    columns:
      - name: tripid
        description: "Primary key for this table"
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
      - name: VendorID
        description: "A code indicating the provider"
      - name: pickup_datetime
        description: "Time when the trip started"
      - name: dropoff_datetime
        description: "Time when the trip ended"
      - name: passenger_count
        description: "Number of passengers"
        tests:
          - not_null
      - name: Trip_distance
        description: "Distance in miles"
      - name: Pickup_locationid
        description: locationid where the meter was engaged.
        tests:
          - relationships:
              to: ref('taxi_zone_lookup')
              field: locationid
              severity: warn
      - name: dropoff_locationid 
        description: locationid where the meter was engaged.
        tests:
          - relationships:
              to: ref('taxi_zone_lookup')
              field: locationid
      - name: RateCodeID 
        description: >
            The final rate code in effect at the end of the trip.
              1= Standard rate
              2=JFK
              3=Newark
              4=Nassau or Westchester
              5=Negotiated fare
              6=Group ride
      - name: Store_and_fwd_flag 
        description: > 
          This flag indicates whether the trip record was held in vehicle
          memory before sending to the vendor, aka “store and forward,”
          because the vehicle did not have a connection to the server.
            Y= store and forward trip
            N = not a store and forward trip
      - name: Dropoff_longitude 
        description: Longitude where the meter was disengaged.
      - name: Dropoff_latitude 
        description: Latitude where the meter was disengaged.
      - name: Payment_type 
        description: >
          A numeric code signifying how the passenger paid for the trip.
        tests: 
          - accepted_values:
              values: "{{ var('payment_type_values') }}"
              severity: warn
              quote: false
      - name: payment_type_description
        description: Description of the payment_type code
      - name: Fare_amount 
        description: > 
          The time-and-distance fare calculated by the meter.
          Extra Miscellaneous extras and surcharges. Currently, this only includes
          the $0.50 and $1 rush hour and overnight charges.
          MTA_tax $0.50 MTA tax that is automatically triggered based on the metered
          rate in use.
      - name: Improvement_surcharge 
        description: > 
          $0.30 improvement surcharge assessed trips at the flag drop. The
          improvement surcharge began being levied in 2015.
      - name: Tip_amount 
        description: > 
          Tip amount. This field is automatically populated for credit card
          tips. Cash tips are not included.
      - name: Tolls_amount 
        description: Total amount of all tolls paid in trip.
      - name: Total_amount 
        description: The total amount charged to passengers. Does not include cash tips.

  - name: stg_yellow_tripdata
    description: "Staging table for Yellow Taxi trip data"
    columns:
      - name: tripid
        description: "Primary key for this table"
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
      - name: VendorID
        description: "A code indicating the provider"
      - name: pickup_datetime
        description: "Time when the trip started"
      - name: dropoff_datetime
        description: "Time when the trip ended"
      - name: passenger_count
        description: "Number of passengers"
        tests:
          - not_null
      - name: Trip_distance
        description: "Distance in miles"
      - name: Pickup_locationid
        description: locationid where the meter was engaged.
        tests:
          - relationships:
              to: ref('taxi_zone_lookup')
              field: locationid
              severity: warn
      - name: dropoff_locationid 
        description: locationid where the meter was engaged.
        tests:
          - relationships:
              to: ref('taxi_zone_lookup')
              field: locationid
      - name: RateCodeID 
        description: >
            The final rate code in effect at the end of the trip.
              1= Standard rate
              2=JFK
              3=Newark
              4=Nassau or Westchester
              5=Negotiated fare
              6=Group ride
      - name: Store_and_fwd_flag 
        description: > 
          This flag indicates whether the trip record was held in vehicle
          memory before sending to the vendor, aka “store and forward,”
          because the vehicle did not have a connection to the server.
            Y= store and forward trip
            N = not a store and forward trip
      - name: Dropoff_longitude 
        description: Longitude where the meter was disengaged.
      - name: Dropoff_latitude 
        description: Latitude where the meter was disengaged.
      - name: Payment_type 
        description: >
          A numeric code signifying how the passenger paid for the trip.
        tests: 
          - accepted_values:
              values: "{{ var('payment_type_values') }}"
              severity: warn
              quote: false
      - name: payment_type_description
        description: Description of the payment_type code
      - name: Fare_amount 
        description: > 
          The time-and-distance fare calculated by the meter.
          Extra Miscellaneous extras and surcharges. Currently, this only includes
          the $0.50 and $1 rush hour and overnight charges.
          MTA_tax $0.50 MTA tax that is automatically triggered based on the metered
          rate in use.
      - name: Improvement_surcharge 
        description: > 
          $0.30 improvement surcharge assessed trips at the flag drop. The
          improvement surcharge began being levied in 2015.
      - name: Tip_amount 
        description: > 
          Tip amount. This field is automatically populated for credit card
          tips. Cash tips are not included.
      - name: Tolls_amount 
        description: Total amount of all tolls paid in trip.
      - name: Total_amount 
        description: The total amount charged to passengers. Does not include cash tips.