# Name your project
name: 'zoomcamp_week4_project'
version: '1.0.0'
config-version: 2

# Profile name
profile: 'default'

# File paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Compilation and cleaning settings
target-path: "target"  # Directory for compiled SQL files
clean-targets:
  - "target"
  - "dbt_packages"

# Define model materialization
models:
  zoomcamp_week4_project:
    staging:
      +materialized: view
      +schema: zoomcamp_week4_hw_staging  
    core:
      +materialized: table
      +schema: zoomcamp_week4_hw_staging  




